### ISSUE TITLE
json file =》 hdfs

### ISSUE THREAD

**Issue by bashhu** [kzk/webhdfs#28]
i have a question：
run.log each line is a json, logstash "input"
```
input{
  file {
	type => "run-log"
	path => "/data/log/run.log"
	codec => "json"
  }
}
```

that "output"
```
output{
     if [type] == "run-log" {
    webhdfs {
      host => "192.168.9.7"
      user => "hue"
      path => "/user/hue/run-log"
    }
	}
}
```

the hadoop "hadoop fs -tail /user/hue/run-log"
`2016-05-06T07:06:43.332Z app-node4.nginxs.net %{message}`

My configuration is wrong? Please tell me，thinks

**Comment by tagomoris** [comment]
How to format data is not about this module, but about logstash output plugin.
Ask the logstash community or repository of that plugin for your problem.

**Comment by bashhu** [comment]
think you
