### ISSUE TITLE
Feature Request: specify two servers for ha cluster

### ISSUE THREAD

**Issue by DanielYWoo** [kzk/webhdfs#29]
Currently we can only specify a single name node, for a ha-cluster, when the name nodes becomes standby, we hope logstash can switch to the new active name node.

**Comment by tagomoris** [comment]
Create two client instances. Fluentd webhdfs plugin does it.
https://github.com/fluent/fluent-plugin-webhdfs

**Comment by DanielYWoo** [comment]
It's already supported but no documented. close it then.
